import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import {
    IMPORTABLE_TABLES, SEQUENCE_BACKED, STRIP_ALWAYS, CATALOG_REMAPS, DROPPED_PARENT_FKS,
} from '../lib/db/importer';

// MECHANICAL invariants over the importer's table policy, checked against schema.sql
// rather than against a hand-maintained list. Both of these were previously enforced
// by nothing at all, and both fail LATE and QUIETLY when they drift:
//
//   * A table imported with explicit identity ids but missing from SEQUENCE_BACKED
//     leaves its sequence at 0. The import looks perfect; the first row created
//     AFTERWARDS collides on the primary key, days later and far from the cause.
//     (This is exactly how the ten Academy tables would have shipped.)
//   * A catalog remap whose embed alias is missing from STRIP_ALWAYS inserts the
//     joined object as if it were a column.
//
// Both are decidable from the source, so they are asserted, not remembered.

const schemaSql = readFileSync(resolve(__dirname, '../schema.sql'), 'utf8');

/** Every table in schema.sql whose PK is a generated identity column (and therefore
 *  owns a sequence that an id-preserving import must re-anchor). */
function identityPkTables(): Set<string> {
    const out = new Set<string>();
    let current = '';
    for (const line of schemaSql.split(/\r?\n/)) {
        const m = /^CREATE TABLE IF NOT EXISTS public\.([a-z0-9_]+)/.exec(line);
        if (m) { current = m[1]; continue; }
        if (current && /GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/.test(line)) out.add(current);
    }
    return out;
}

/** Every table declared anywhere in schema.sql. */
function schemaTables(): Set<string> {
    return new Set([...schemaSql.matchAll(/^CREATE TABLE IF NOT EXISTS public\.([a-z0-9_]+)/gm)].map((m) => m[1]));
}

describe('importer table-set invariants', () => {
    it('sanity: schema.sql parses into a plausible table inventory', () => {
        expect(schemaTables().size).toBeGreaterThan(80);
        expect(identityPkTables().size).toBeGreaterThan(50);
        expect(identityPkTables().has('user_ships')).toBe(true);
        expect(identityPkTables().has('academy_lessons')).toBe(true);
        // uuid PKs must NOT be picked up by the parser.
        expect(identityPkTables().has('academy_courses')).toBe(false);
        expect(identityPkTables().has('marketplace_listings')).toBe(false);
    });

    it('every importable table actually exists in this instance schema', () => {
        const known = schemaTables();
        const unknown = [...IMPORTABLE_TABLES].filter((t) => !known.has(t));
        expect(unknown).toEqual([]);
    });

    it('SEQUENCE_BACKED is EXACTLY the importable tables with an identity PK', () => {
        const identity = identityPkTables();
        // Missing → the first post-import insert collides on the PK (silent, delayed).
        const missing = [...IMPORTABLE_TABLES].filter((t) => identity.has(t) && !SEQUENCE_BACKED.has(t)).sort();
        expect(missing, 'importable identity-PK tables missing from SEQUENCE_BACKED').toEqual([]);
        // Extra → a wasted (harmless) RPC, but it means the two lists have drifted.
        const notIdentity = [...SEQUENCE_BACKED].filter((t) => !identity.has(t)).sort();
        expect(notIdentity, 'SEQUENCE_BACKED entries whose PK is not a sequence').toEqual([]);
        const notImportable = [...SEQUENCE_BACKED].filter((t) => !IMPORTABLE_TABLES.has(t)).sort();
        expect(notImportable, 'SEQUENCE_BACKED entries that are never imported').toEqual([]);
    });

    it('STRIP_ALWAYS covers every catalog-remap embed alias', () => {
        const aliases = Object.values(CATALOG_REMAPS).map((r) => r.embedAlias);
        const unstripped = aliases.filter((a) => !STRIP_ALWAYS.has(a)).sort();
        expect(unstripped, 'embed aliases that would be inserted as columns').toEqual([]);
    });

    it('every catalog remap names a real catalog table and selects no wildcard', () => {
        const known = schemaTables();
        for (const [table, remap] of Object.entries(CATALOG_REMAPS)) {
            expect(known.has(table), `${table} is not a table in schema.sql`).toBe(true);
            expect(known.has(remap.catalogTable), `${remap.catalogTable} is not a table in schema.sql`).toBe(true);
            expect(remap.catalogSelect).not.toContain('*');
            // The remap's own FK column must be selectable by name — a remap whose
            // key columns are not in catalogSelect can never match anything.
            expect(remap.catalogSelect.split(',').map((c) => c.trim())).toContain('id');
        }
    });

    it('every ship remap emits all three key forms in precision order, and selects the columns they need', () => {
        // The two platform_ships consumers must key the catalog IDENTICALLY — the index
        // is cached per catalog table, so a divergence would silently mis-resolve one of
        // them. Asserting the emitted forms (rather than object identity) also pins the
        // precision order the lookup depends on: an exact external id must always be
        // tried before the name fallback.
        const shipRemaps = Object.entries(CATALOG_REMAPS).filter(([, r]) => r.catalogTable === 'platform_ships');
        expect(shipRemaps.map(([t]) => t).sort()).toEqual(['operation_participants', 'user_ships']);
        for (const [table, remap] of shipRemaps) {
            expect(remap.keysOf({ external_uuid: 'U', external_api_id: 42, name: 'Cutlass Black', manufacturer: 'Drake Interplanetary' }),
                `${table} key order`).toEqual(['a:42', 'u:U', 'n:cutlass black|drake interplanetary']);
            const cols = remap.catalogSelect.split(',').map((c) => c.trim());
            expect(cols).toEqual(expect.arrayContaining(['id', 'external_uuid', 'external_api_id', 'name', 'manufacturer']));
        }
    });

    it('DROPPED_PARENT_FKS covers every importable FK into a table whose rows a required remap can drop', () => {
        // A `required: true` remap DROPS rows when the catalog does not resolve. Every
        // importable table with an FK into one of those tables must be listed, or its
        // rows FK-fail one at a time in the row-by-row fallback and get reported as a
        // generic "rejected by the database" — hiding that ONE unsynced catalog caused
        // all of it. Derived from schema.sql so the list cannot silently fall behind a
        // new FK or a new required remap.
        const droppable = new Set(Object.entries(CATALOG_REMAPS).filter(([, r]) => r.required).map(([t]) => t));
        expect(droppable.size).toBeGreaterThan(0);

        const declared = new Set<string>();
        for (const [table, fks] of Object.entries(DROPPED_PARENT_FKS)) {
            for (const fk of fks) declared.add(`${table}.${fk.col}->${fk.parent}`);
        }

        // Parse every FK in schema.sql as (table, column, parentTable, notNull).
        const missing: string[] = [];
        const wrongNullability: string[] = [];
        let current = '';
        for (const line of schemaSql.split(/\r?\n/)) {
            const t = /^CREATE TABLE IF NOT EXISTS public\.([a-z0-9_]+)/.exec(line);
            if (t) { current = t[1]; continue; }
            const fk = /^\s+([a-z0-9_]+)\s+[a-z]+\s*(NOT NULL)?\s*REFERENCES public\.([a-z0-9_]+)\(/.exec(line);
            if (!fk || !current) continue;
            const [, col, notNull, parent] = fk;
            if (!droppable.has(parent) || !IMPORTABLE_TABLES.has(current) || !IMPORTABLE_TABLES.has(parent)) continue;
            // The remapped FK column itself is handled by the remap, not the cascade.
            if (CATALOG_REMAPS[current]?.fkColumn === col) continue;
            const key = `${current}.${col}->${parent}`;
            if (!declared.has(key)) { missing.push(key); continue; }
            const entry = DROPPED_PARENT_FKS[current].find((e) => e.col === col)!;
            if (entry.nullable === !!notNull) wrongNullability.push(`${key} (declared nullable:${entry.nullable}, schema says ${notNull ? 'NOT NULL' : 'nullable'})`);
        }
        expect(missing, 'FKs into a droppable parent with no DROPPED_PARENT_FKS entry').toEqual([]);
        expect(wrongNullability, 'DROPPED_PARENT_FKS nullability disagrees with schema.sql').toEqual([]);

        // …and nothing declared that is not a real FK into a droppable parent.
        for (const [table, fks] of Object.entries(DROPPED_PARENT_FKS)) {
            expect(IMPORTABLE_TABLES.has(table), `${table} is not importable`).toBe(true);
            for (const fk of fks) expect(droppable.has(fk.parent), `${fk.parent} is not a droppable parent`).toBe(true);
        }
    });

    it('the bilateral marketplace tables are never importable', () => {
        // Contracts / ratings / reports name a SECOND tenant (buyer_org_id) or platform
        // moderation state. The hosted side does not export them and this fork must not
        // invent them — listings only.
        for (const t of ['marketplace_contracts', 'marketplace_contract_milestones', 'marketplace_ratings', 'marketplace_reports']) {
            expect(IMPORTABLE_TABLES.has(t), `${t} must not be importable`).toBe(false);
        }
        expect(IMPORTABLE_TABLES.has('marketplace_listings')).toBe(true);
        // The category taxonomy is seeded locally and is the re-map TARGET, not cargo.
        expect(IMPORTABLE_TABLES.has('marketplace_categories')).toBe(false);
        expect(SEQUENCE_BACKED.has('marketplace_categories')).toBe(false);
    });

    it('all ten academy tables are importable, and only the identity-PK seven are sequence-backed', () => {
        const uuidPk = ['academy_courses', 'academy_sessions', 'academy_enrollments'];
        const identityPk = [
            'academy_course_instructors', 'academy_modules', 'academy_lessons', 'academy_outcomes',
            'academy_session_instructors', 'academy_lesson_progress', 'academy_outcome_results',
        ];
        for (const t of [...uuidPk, ...identityPk]) expect(IMPORTABLE_TABLES.has(t), `${t} importable`).toBe(true);
        for (const t of identityPk) expect(SEQUENCE_BACKED.has(t), `${t} sequence-backed`).toBe(true);
        for (const t of uuidPk) expect(SEQUENCE_BACKED.has(t), `${t} has a uuid PK — no sequence`).toBe(false);
    });
});
